config:
  target: "http://localhost:3000"
  phases:
    - duration: 60
      arrivalRate: 5
      name: Warm up

scenarios:
  - name: "Search all products"
    flow:
      - get:
          url: "/products"